### PR TITLE
01 python

### PR DESCRIPTION
**Pull request by mspieg**
small modifications and additions to 01_python.ipynb notebook

- added a little on checking types with isinstance
- added a short example of exception handling 
- added a bit on  peer review (because the exception example is actually a crappy piece of code ;^)

### CODE REVIEW

**Comment by mandli** [comment]
Heh, yes it is.

You may want to also add the debugging comment from https://github.com/mandli/numerical-methods-pdes/blob/master/01_python.ipynb that has a pointer to a tutorial by @jhamrick s well.

**Comment by mspieg** [comment]
adding the debugging section might break travis.
Oh and my function is still stupid but at least the docstrings are numpy style compliant ;^)

**Comment by mandli** [comment]
I usually comment out those pieces until I use it in class.  Otherwise there's no good way to that but still past the tests meaningfully.

**Comment by mspieg** [comment]
Okay, let me comment that out and push again.

**Pull request merged**
