### PR TITLE
Following the lecture

### PR DESCRIPTION
**Pull request by vincentqb**
I mostly changed the align environment to $$ that I couldn't parse for the presentation. 

Two more things:

* Line 72 with the <,> was also causing some problems, so I replaced by \langle and \rangle.

* Also, this sentence was not clear to me:
"Another way to write this is that $x_k$ is orthogonal to all the rest of the vectors in the set $X$."
and I was understanding it as:
"Another way to write this is that any $x_k$ has a component orthogonal to all the rest of the vectors in the set $X$."
Is that what you meant?

### CODE REVIEW

**Comment by mandli** [comment]
@vincentqb What system were you running this on and what version of Jupyter?  I am surprised that the aligns did not work.

**Comment by mandli** [comment]
Also, for the orthogonality, the precise statement should be $\forall v \in X, <x_k, v> = 0$ except when $v = x_k$.  Does that better represent the statement?

**Comment by vincentqb** [comment]
On Ubuntu 16.04, from Jupyter notebook's about:
The version of the notebook server is 4.2.3 and is running on:
Python 3.5.2 |Anaconda 2.5.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Python 3.5.2 |Anaconda 2.5.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
IPython 5.1.0 -- An enhanced Interactive Python.

**Comment by mandli** [comment]
Huh, the version of Jupyter and IPython are the same.  The only big difference is the version of Python (I usually use 2.7 still).  Seems odd that it would have regressed though.  Does the following fix the rendering?

https://github.com/jupyter/nbviewer/issues/590

**Comment by vincentqb** [comment]
X is a list of vectors, not necessarily forming a linear space, right? I understand x_k to be a generic linear combination of vectors in X that may or may not be in X. Is that correct? For example, if I take x_k as (1,0) but X={(0,1),(1,1)} then x_k is a linear combination of vectors in X, but x_k is not orthogonal to the vectors in X. Did I get x_k and X right?

**Comment by mandli** [comment]
X is a set of linearly independent vectors.  From the wording I see how this could be confusing though as x_k \in X but in the cell above is written as a contradiction of the statement.

**Comment by mandli** [comment]
I changed some of the aligns and fixed the angled brackets in commit e3a0bca5b5c2d53a16a122eea5c20a08b1387adc

**Pull request closed without merging**
