### PR TITLE
Bugfix/15_LA

### PR DESCRIPTION
**Pull request by x94carbone**
Fixed the analytical error in the last slide. Not sure if the version change at the very end is important. I'm not sure if that's relevant or not, or where it comes from frankly.

### CODE REVIEW

**Comment by mandli** [comment]
The checks are failing because of an issue in another notebook.  Can you merge in the changes to the corrected notebook (`git merge --ff-only` hopefully should do the trick) and push up the update to this PR?

**Comment by x94carbone** [comment]
When I do that I get an "already up to date" message from git. When you say merging in the changes to the corrected notebook, what exactly are you referring to? I'm sorry I'm still new to this. Thanks!

**Comment by mandli** [comment]
You probably need to `fetch` from the repository first.  Make sure to fetch from mine and not yours.  You may need to add my repository as a remote
```
git remote add mandli git://github.com/mandli/intro-numerical-methods
```
should do that.  Then you can do a 
```
git fetch mandli
git merge --ff-only mandli/master
```
should then get all the changes up to date with my master.

**Comment by x94carbone** [comment]
I'm getting the error "fatal: Not possible to fast-forward, aborting."

Is this an error with the merge itself? Perhaps if I understood more about the problem I could troubleshoot it a bit too. 

Let me explain what I did, then maybe it'll be more clear what to do now.
1. Forked on GitHub.
2. Cloned locally. 
3. Added upstream `git remote add upstream git://github.com/mandli/intro-numerical-methods`
4. Pulled from yours, pushed to mine (in master)
5. Created branch bugfix/15 `checkout -b bugfix/15`
6. Did work, commits, pushed to my remote `git push -u origin bugfix/15`
7. Opened PR on GitHub.

From there, I tried to follow your directions above in the bugfix/15 branch. Am I doing something wrong here? Thanks for working with me on this. I realize its more trouble than its worth but its a nice learning process for me.

**Comment by mandli** [comment]
You can try to do a merge instead of a fast-forward merge.  Also you can do a diff between your fix and the master to see what has changed.  Also you may want to see what commit you branched from to see what may have changed between your version and mine.

**Comment by x94carbone** [comment]
Ok just tried that. Pretty cool how it automatically updates the pull request. Let's see what happens.

Also, is the version change 3.6.3 -> 3.6.2 going to be a problem?

**Comment by mandli** [comment]
The version should not be an issue (it's just kind of annoying).

**Comment by x94carbone** [comment]
Ok great, thank you! Glad I could help.

**Pull request merged**
