### PR TITLE
Fix root finding newton derivation

### PR DESCRIPTION
**Pull request by mandli**
Addresses #3 pointed out by @yeejoh.

### CODE REVIEW

**Comment by mandli** [comment]
@yeejoh, can you look at this and make sure this addresses your issue?

**Comment by yeejoh** [comment]
There is a missing square notation, `^2`, of `f'(x^*)` at the denominator of `g'(x^*)`.

And I think `f'^2(x^*)` is less confusing than `f'(x^*)^2`, like `\sin ^2 x` not `\sin (x) ^2`.

**Comment by mandli** [comment]
Ah, thanks, was not being careful.

As for the notation, I generally agree with you but having two superscripts there I think is more confusing and less standard.

**Comment by yeejoh** [comment]
I believe now they're correct. Thanks for responding.

A notation is a good notation as long as it's unambiguous. I can live will that. :stuck_out_tongue_winking_eye:

**Comment by mandli** [comment]
Agree notationally.

**Pull request merged**
