### PR TITLE
Changes to wording to the intro_numerical_methods notebook

### PR DESCRIPTION
**Pull request by KellyBlack**
Made some changes to the intro notebook. Provided some more details and turned some of the snippets into complete sentences.

### CODE REVIEW

**Comment by mandli** [comment]
Thanks @KellyBlack!

**Comment by KellyBlack** [comment]
Thank you! Your work on this set of notebooks is greatly appreciated. We are considering using them for our numerical methods class at UGA. We would like to add some homework questions. Would that be something you would be interested in including if we make them up? Also, what is the best way to coordinate if we wish to add more examples to make sure it is something you would like to include in your branch?

**Comment by mandli** [comment]
Hi @KellyBlack, there are actually a bunch of hw questions associated with these notebooks but that I keep in another, private repository (they also have answers).  I could put the non-answered homework publicly so that we can continue to add to them or just share the private repository with you.  As for the additional examples I would be happy to include them in these notebooks!

**Comment by KellyBlack** [comment]
Having homework questions available would be ideal. Anything you are willing to add would be greatly appreciated. 

With respect to extra examples, do you have a process or branch that you prefer to use to review them? For example, I was thinking of adding a section on stability in your notebook that covers error. In particular going over the classic example of a second order difference equation where one of the homogeneous solutions grows geometrically and the interplay between numerical error and the stability of the algorithm. 

Some folks do not like that example because it can conflate truncation error with stability so I was a bit hesitant to just throw it out there.

**Comment by mandli** [comment]
I will invite you to the private repository then.

For adding content I would say doing the normal fork and pull request would be ideal.

For the example do you mean something like example 1 from the error notebook?  In any case I think it best to have as many examples that we can have and let individuals pick and choose which examples to use/present.

**Comment by KellyBlack** [comment]
Got it, thank you! I will take a look. Is it okay to remove the solutions and share the homework questions with students?

In terms of the example, I was thinking about something along the lines of solutions to
x_{n+1} = -5.5 x_n + 3 x_{n-1}, with x_0 = 1/3, x_1=1/6.
Like in the book Afternotes on Numerical Analysis, pp. 63-65 and the interplay of rounding error and stability.

Also, we added an appendix on the mean value theorem including how it is used to derive  the error term for Taylor series:
https://github.com/KellyBlack/intro-numerical-methods/blob/UGA/04_error.ipynb

**Comment by mandli** [comment]
All sounds good to me.

The homework notebooks are run through nbgrader that automatically strips the solutions from the notebooks for release.  This is easily done and sharable of course.

**Pull request merged**
