### PR TITLE
Added a section on matrix operations for the numpy examples

### PR DESCRIPTION
**Pull request by KellyBlack**
Added information about defining an identity matrix, multiplying an array, and manipulating a single entry in an array using the numpy library.

### CODE REVIEW

**Comment by mandli** [comment]
I am not sure what the best way to test for failed checks as I think they are important to show.  I have in the past either caught the exception and printed it instead (showing the try-except block functionality) or had the correct version written in the notebook and then change it to fail but not commit that.

**Comment by KellyBlack** [comment]
I am not sure. When I have used matlab I have the students use codes where errors occur. The reason is that I feel it is important for them to see error messages and learn how to read them. Using a try/except block is good, but it may be a bit much in the intro on python.

If I comment out the code and add a note about removing it and executing the block would that be acceptable?

**Comment by mandli** [comment]
I think that would be fine.

**Comment by KellyBlack** [comment]
I commented out the line and changed the markup to let people know to uncomment the line and read the error message. Will push it to my repo and add the pull request soon.

**Pull request merged**
